<html>
<head>
<title>Beginner Guide to Exception and Exception Handling in Python</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">Python 异常和异常处理初学者指南</h1>
<blockquote>原文：<a href="https://towardsdatascience.com/exception-handling-in-python-85f49801b131?source=collection_archive---------25-----------------------#2020-05-07">https://towardsdatascience.com/exception-handling-in-python-85f49801b131?source=collection_archive---------25-----------------------#2020-05-07</a></blockquote><div><div class="fc ih ii ij ik il"/><div class="im in io ip iq"><div class=""/><div class=""><h2 id="4ab2" class="pw-subtitle-paragraph jq is it bd b jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh dk translated">Python 中的异常处理是通过使用 try except 子句来完成的</h2></div><figure class="kj kk kl km gt kn gh gi paragraph-image"><div role="button" tabindex="0" class="ko kp di kq bf kr"><div class="gh gi ki"><img src="../Images/e1cfbddb26a081df30c0856b1c27f912.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/0*2EIe4Et3J3ZNJaaq"/></div></div><p class="ku kv gj gh gi kw kx bd b be z dk translated">照片由<a class="ae ky" href="https://unsplash.com/@hiteshchoudhary?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank"> Hitesh Choudhary </a>在<a class="ae ky" href="https://unsplash.com?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank"> Unsplash </a>上拍摄</p></figure></div><div class="ab cl kz la hx lb" role="separator"><span class="lc bw bk ld le lf"/><span class="lc bw bk ld le lf"/><span class="lc bw bk ld le"/></div><div class="im in io ip iq"><h1 id="949f" class="lg lh it bd li lj lk ll lm ln lo lp lq jz lr ka ls kc lt kd lu kf lv kg lw lx bi translated">介绍</h1><p id="48ba" class="pw-post-body-paragraph ly lz it ma b mb mc ju md me mf jx mg mh mi mj mk ml mm mn mo mp mq mr ms mt im bi translated">在本教程中，我们将学习如何使用 try except 子句在 Python 中处理异常。</p><p id="efd9" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">但是首先，什么是例外？🤔</p><p id="97ea" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">异常是当代码的执行导致意外结果时，由我们的代码引发的错误。通常，异常会有一个错误类型和一条错误消息。一些例子如下。</p><pre class="kj kk kl km gt mz na nb nc aw nd bi"><span id="4297" class="ne lh it na b gy nf ng l nh ni">ZeroDivisionError: division by zero<br/>TypeError: must be str, not int</span></pre><p id="4288" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated"><code class="fe nj nk nl na b">ZeroDivisionError</code>和<code class="fe nj nk nl na b">TypeError</code>是错误类型，冒号后的文本是错误消息。错误消息通常描述错误类型。</p><p id="3f13" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">每一个好的代码和应用程序都会处理异常，以保持用户体验的流畅和无缝。那么，让我们来学习如何做到这一点，好吗？🙂</p></div><div class="ab cl kz la hx lb" role="separator"><span class="lc bw bk ld le lf"/><span class="lc bw bk ld le lf"/><span class="lc bw bk ld le"/></div><div class="im in io ip iq"><h1 id="67ba" class="lg lh it bd li lj lk ll lm ln lo lp lq jz lr ka ls kc lt kd lu kf lv kg lw lx bi translated">内置异常</h1><p id="da86" class="pw-post-body-paragraph ly lz it ma b mb mc ju md me mf jx mg mh mi mj mk ml mm mn mo mp mq mr ms mt im bi translated">在 Python 中，所有内置的异常都是从<code class="fe nj nk nl na b">BaseException</code>类中派生出来的。直接继承<code class="fe nj nk nl na b">BaseException</code>类的异常类有:<code class="fe nj nk nl na b">Exception</code>、<code class="fe nj nk nl na b">GeneratorExit</code>、<code class="fe nj nk nl na b">KeyboardInterrupt</code>和<code class="fe nj nk nl na b">SystemExit</code>。在本教程中，我们将重点关注<code class="fe nj nk nl na b">Exception</code>类。</p><p id="6798" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">在许多情况下，我们希望定义自己的自定义异常类。这样做的好处是，我们可以通过用甚至非程序员也能理解的简单英语来指出程序中出现的错误。</p><p id="0d02" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">要定义一个定制的异常类，我们需要从<code class="fe nj nk nl na b">Exception</code>类继承，而不是像官方 Python 3 文档<a class="ae ky" href="https://docs.python.org/3/library/exceptions.html" rel="noopener ugc nofollow" target="_blank">中建议的那样从<code class="fe nj nk nl na b">BaseException</code>类继承。</a></p><p id="b99f" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">酷毙了。现在我们对异常有了一些基本的了解，让我们来看一些例子。</p></div><div class="ab cl kz la hx lb" role="separator"><span class="lc bw bk ld le lf"/><span class="lc bw bk ld le lf"/><span class="lc bw bk ld le"/></div><div class="im in io ip iq"><h1 id="d54f" class="lg lh it bd li lj lk ll lm ln lo lp lq jz lr ka ls kc lt kd lu kf lv kg lw lx bi translated">常见例外</h1><p id="2d8a" class="pw-post-body-paragraph ly lz it ma b mb mc ju md me mf jx mg mh mi mj mk ml mm mn mo mp mq mr ms mt im bi translated">现在，我们将看看在学习 Python 编程时可能遇到的一些最基本和最常见的异常。</p><h2 id="559d" class="ne lh it bd li nm nn dn lm no np dp lq mh nq nr ls ml ns nt lu mp nu nv lw nw bi translated">值错误</h2><p id="6348" class="pw-post-body-paragraph ly lz it ma b mb mc ju md me mf jx mg mh mi mj mk ml mm mn mo mp mq mr ms mt im bi translated">当我们传入一个正确类型的值，但该值是错误的时，就会引发这个异常。举个例子，假设我们想把一个字符串转换成一个整数。</p><pre class="kj kk kl km gt mz na nb nc aw nd bi"><span id="307d" class="ne lh it na b gy nf ng l nh ni">int("5")  // 5</span></pre><p id="7113" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">这很好，对吧？现在，看看当我们传递一个不能转换成整数的字符串时会发生什么。</p><pre class="kj kk kl km gt mz na nb nc aw nd bi"><span id="7d67" class="ne lh it na b gy nf ng l nh ni">int("five")</span><span id="aeeb" class="ne lh it na b gy nx ng l nh ni">Traceback (most recent call last):<br/>  File "&lt;input&gt;", line 1, in &lt;module&gt;<br/>ValueError: invalid literal for int() with base 10: 'five'</span></pre><p id="54f1" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">现在说得通了吧？在第二个例子中，尽管参数的类型是好的，但是值是不正确的。</p><h2 id="cc8a" class="ne lh it bd li nm nn dn lm no np dp lq mh nq nr ls ml ns nt lu mp nu nv lw nw bi translated">索引错误</h2><p id="7311" class="pw-post-body-paragraph ly lz it ma b mb mc ju md me mf jx mg mh mi mj mk ml mm mn mo mp mq mr ms mt im bi translated">这个异常告诉我们，我们正试图通过超出范围的索引来访问集合中的项目或元素(例如，字符串或列表对象)。</p><pre class="kj kk kl km gt mz na nb nc aw nd bi"><span id="8cad" class="ne lh it na b gy nf ng l nh ni">some_list = [1, 2, 3, 4]<br/>some_list[5]</span><span id="f681" class="ne lh it na b gy nx ng l nh ni">Traceback (most recent call last):<br/>  File "&lt;input&gt;", line 1, in &lt;module&gt;<br/>IndexError: list index out of range</span></pre><p id="4aa1" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">在这个例子中，<code class="fe nj nk nl na b">some_list</code>的最大索引是 3，我们要求程序访问索引为<code class="fe nj nk nl na b">[5]</code>的元素。因为该索引不存在(或者超出范围)，所以抛出<code class="fe nj nk nl na b">IndexError</code>异常。</p><h2 id="8722" class="ne lh it bd li nm nn dn lm no np dp lq mh nq nr ls ml ns nt lu mp nu nv lw nw bi translated">类型错误</h2><p id="ed3a" class="pw-post-body-paragraph ly lz it ma b mb mc ju md me mf jx mg mh mi mj mk ml mm mn mo mp mq mr ms mt im bi translated">与<code class="fe nj nk nl na b">ValueError</code>不同，当我们传递给函数或表达式的参数或对象的类型是错误的类型时，就会引发这个异常。</p><pre class="kj kk kl km gt mz na nb nc aw nd bi"><span id="bf44" class="ne lh it na b gy nf ng l nh ni">100 + "two hundred"</span><span id="8dbd" class="ne lh it na b gy nx ng l nh ni">Traceback (most recent call last):<br/>  File "&lt;input&gt;", line 1, in &lt;module&gt;<br/>TypeError: unsupported operand type(s) for +: 'int' and 'str'</span></pre><p id="aec3" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">这里的错误信息非常清楚。它告诉我们<code class="fe nj nk nl na b">+</code>操作符不能用于类型为<code class="fe nj nk nl na b">int</code>和<code class="fe nj nk nl na b">str</code>的对象。</p><h2 id="c516" class="ne lh it bd li nm nn dn lm no np dp lq mh nq nr ls ml ns nt lu mp nu nv lw nw bi translated">名称错误</h2><p id="c4c5" class="pw-post-body-paragraph ly lz it ma b mb mc ju md me mf jx mg mh mi mj mk ml mm mn mo mp mq mr ms mt im bi translated">每当我们试图使用一个不存在或尚未定义的变量时，就会抛出这个异常。</p><pre class="kj kk kl km gt mz na nb nc aw nd bi"><span id="9b10" class="ne lh it na b gy nf ng l nh ni">a = "defined"</span><span id="1201" class="ne lh it na b gy nx ng l nh ni">print(b)</span><span id="8214" class="ne lh it na b gy nx ng l nh ni">Traceback (most recent call last):<br/>  File "&lt;input&gt;", line 1, in &lt;module&gt;<br/>NameError: name 'b' is not defined</span></pre><p id="8583" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">同样，错误信息非常清楚。这个不用多解释了。🙂</p><p id="32ee" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">还有许多更常见的异常，但我希望这已经是足够的例子了。</p><p id="ccd7" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">现在，你可能会问，写着<code class="fe nj nk nl na b">Traceback (most recent call last)</code>的前几行是什么？好吧，让我们在下一节讨论一下。</p></div><div class="ab cl kz la hx lb" role="separator"><span class="lc bw bk ld le lf"/><span class="lc bw bk ld le lf"/><span class="lc bw bk ld le"/></div><div class="im in io ip iq"><figure class="kj kk kl km gt kn gh gi paragraph-image"><div role="button" tabindex="0" class="ko kp di kq bf kr"><div class="gh gi ny"><img src="../Images/1891a749a0836de145f862aaca0d00bd.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/0*WAiMbiQjEmoSiTKY"/></div></div><p class="ku kv gj gh gi kw kx bd b be z dk translated">照片由<a class="ae ky" href="https://unsplash.com/@martenbjork?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank">马丁·比约克</a>在<a class="ae ky" href="https://unsplash.com?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank"> Unsplash </a>上拍摄</p></figure></div><div class="ab cl kz la hx lb" role="separator"><span class="lc bw bk ld le lf"/><span class="lc bw bk ld le lf"/><span class="lc bw bk ld le"/></div><div class="im in io ip iq"><h1 id="d5bf" class="lg lh it bd li lj lk ll lm ln lo lp lq jz lr ka ls kc lt kd lu kf lv kg lw lx bi translated">回溯(或堆栈跟踪)</h1><p id="db3d" class="pw-post-body-paragraph ly lz it ma b mb mc ju md me mf jx mg mh mi mj mk ml mm mn mo mp mq mr ms mt im bi translated">在上一节的所有示例异常中，有一点值得一提，那就是异常类型和消息之前的部分。这部分被称为回溯或堆栈跟踪。</p><pre class="kj kk kl km gt mz na nb nc aw nd bi"><span id="ee4c" class="ne lh it na b gy nf ng l nh ni">Traceback (most recent call last):<br/>  File "&lt;input&gt;", line 1, in &lt;module&gt;</span></pre><p id="9426" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">当我们的代码比上面的例子复杂得多时，这是很有用的，我敢打赌一定会如此，尤其是我们的应用程序代码。回溯或堆栈跟踪本质上告诉我们代码执行的顺序，从最新的(顶部)到最早的(底部)。</p><p id="973a" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">让我们看一些来自 Python 官方<a class="ae ky" href="https://docs.python.org/2/library/traceback.html" rel="noopener ugc nofollow" target="_blank">文档</a>的例子。</p><pre class="kj kk kl km gt mz na nb nc aw nd bi"><span id="0050" class="ne lh it na b gy nf ng l nh ni">Traceback (most recent call last):<br/>  File "&lt;doctest...&gt;", line 10, <strong class="na iu">in</strong> &lt;module&gt;<br/>    lumberjack()<br/>  File "&lt;doctest...&gt;", line 4, <strong class="na iu">in</strong> lumberjack<br/>    bright_side_of_death()<br/>IndexError: tuple index out of range</span></pre><p id="3f4f" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">这里，回溯告诉我们导致<code class="fe nj nk nl na b">IndexError</code>异常的最后一次代码执行位于第 10 行，特别是在调用<code class="fe nj nk nl na b">lumberjack()</code>函数时。</p><p id="eb5d" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">它还告诉我们，在调用<code class="fe nj nk nl na b">lumberjack()</code>函数之前，我们的程序从第 4 行开始执行<code class="fe nj nk nl na b">bright_side_of_death()</code>函数。</p><p id="3784" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">在真实世界的应用程序中，我们的代码由许多模块组成，回溯将有助于调试。因为它指导我们哪里出了问题，在哪里以及执行的顺序。</p></div><div class="ab cl kz la hx lb" role="separator"><span class="lc bw bk ld le lf"/><span class="lc bw bk ld le lf"/><span class="lc bw bk ld le"/></div><div class="im in io ip iq"><h1 id="ee42" class="lg lh it bd li lj lk ll lm ln lo lp lq jz lr ka ls kc lt kd lu kf lv kg lw lx bi translated">用户定义的异常</h1><p id="1e42" class="pw-post-body-paragraph ly lz it ma b mb mc ju md me mf jx mg mh mi mj mk ml mm mn mo mp mq mr ms mt im bi translated">如前所述，Python 允许我们定义自己的定制异常。为此，我们需要定义一个继承了<code class="fe nj nk nl na b">Exception</code>类的类。</p><pre class="kj kk kl km gt mz na nb nc aw nd bi"><span id="2f3c" class="ne lh it na b gy nf ng l nh ni">class MyCustomException(Exception):<br/>    def __init__(self, code, message):<br/>        self.code = code<br/>        self.message = message</span></pre><p id="1b0f" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">在讨论这个问题的同时，让我们看看如何在代码中引发一个异常。我们现在将定义一个抛出<code class="fe nj nk nl na b">MyCustomException</code>的函数。</p><pre class="kj kk kl km gt mz na nb nc aw nd bi"><span id="9ae9" class="ne lh it na b gy nf ng l nh ni">def process_card(card_type):<br/>    if card_type == "amex":<br/>        raise MyCustomException("UNSUPPORTED_CARD_TYPE", "The card type used is not currently supported.")<br/>    else:<br/>        return "OK"</span></pre><p id="98d8" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">现在，让我们通过传递<code class="fe nj nk nl na b">"amex"</code>作为参数来调用<code class="fe nj nk nl na b">process_card</code>，这样它将抛出<code class="fe nj nk nl na b">MyCustomException</code>。</p><pre class="kj kk kl km gt mz na nb nc aw nd bi"><span id="be68" class="ne lh it na b gy nf ng l nh ni">process_card("amex")</span><span id="c925" class="ne lh it na b gy nx ng l nh ni">Traceback (most recent call last):<br/>  File "&lt;input&gt;", line 1, in &lt;module&gt;<br/>  File "&lt;input&gt;", line 3, in process_card<br/>MyCustomException: ('UNSUPPORTED_CARD_TYPE', 'The card type used is not currently supported.')</span></pre><p id="17f1" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">完美！因此，为了从我们的代码中抛出一个异常，要使用的关键字是<code class="fe nj nk nl na b">raise</code>关键字。</p><p id="aaad" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">好了，我希望现在你已经很好地理解了什么是异常，尤其是在 Python 中。接下来，我们要学习如何处理它。</p></div><div class="ab cl kz la hx lb" role="separator"><span class="lc bw bk ld le lf"/><span class="lc bw bk ld le lf"/><span class="lc bw bk ld le"/></div><div class="im in io ip iq"><figure class="kj kk kl km gt kn gh gi paragraph-image"><div role="button" tabindex="0" class="ko kp di kq bf kr"><div class="gh gi nz"><img src="../Images/ffbf5e1ffa30d28f245e4601c5c75624.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/0*c89qdf2WAymK3q_b"/></div></div><p class="ku kv gj gh gi kw kx bd b be z dk translated">Andrés Canchón 在<a class="ae ky" href="https://unsplash.com?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank"> Unsplash </a>拍摄的照片</p></figure></div><div class="ab cl kz la hx lb" role="separator"><span class="lc bw bk ld le lf"/><span class="lc bw bk ld le lf"/><span class="lc bw bk ld le"/></div><div class="im in io ip iq"><h1 id="b919" class="lg lh it bd li lj lk ll lm ln lo lp lq jz lr ka ls kc lt kd lu kf lv kg lw lx bi translated">用 Try Except 子句处理异常</h1><p id="25d8" class="pw-post-body-paragraph ly lz it ma b mb mc ju md me mf jx mg mh mi mj mk ml mm mn mo mp mq mr ms mt im bi translated">Python 为我们提供了 try except 子句来处理代码可能引发的异常。try except 子句的基本结构如下。</p><pre class="kj kk kl km gt mz na nb nc aw nd bi"><span id="ad00" class="ne lh it na b gy nf ng l nh ni">try:<br/>    // some codes<br/>except:<br/>    // what to do when the codes in try raise an exception</span></pre><p id="6ae3" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">简单地说，try except 子句基本上是在说，“尝试这样做，除非有错误，然后改为这样做”。</p><p id="aeb5" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">对于如何处理从<code class="fe nj nk nl na b">try</code>块抛出的异常，有几个选项。我们来讨论一下。</p><h2 id="a625" class="ne lh it bd li nm nn dn lm no np dp lq mh nq nr ls ml ns nt lu mp nu nv lw nw bi translated">重新引发异常</h2><p id="437d" class="pw-post-body-paragraph ly lz it ma b mb mc ju md me mf jx mg mh mi mj mk ml mm mn mo mp mq mr ms mt im bi translated">让我们看看如何编写 try except 语句，通过重新引发异常来处理异常。</p><p id="470b" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">首先，让我们定义一个函数，它接受两个输入参数并返回它们的和。</p><pre class="kj kk kl km gt mz na nb nc aw nd bi"><span id="cc2c" class="ne lh it na b gy nf ng l nh ni">def myfunction(a, b):<br/>    return a + b</span></pre><p id="1302" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">接下来，让我们将它包装在一个 try except 子句中，并传递错误类型的输入参数，这样函数将引发<code class="fe nj nk nl na b">TypeError</code>异常。</p><pre class="kj kk kl km gt mz na nb nc aw nd bi"><span id="a2e2" class="ne lh it na b gy nf ng l nh ni">try:<br/>    myfunction(100, "one hundred")<br/>except:<br/>    raise</span><span id="20fe" class="ne lh it na b gy nx ng l nh ni">Traceback (most recent call last):<br/>  File "&lt;input&gt;", line 2, in &lt;module&gt;<br/>  File "&lt;input&gt;", line 2, in myfunction<br/>TypeError: unsupported operand type(s) for +: 'int' and 'str'</span></pre><p id="b9a8" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">这与我们不在 try except 子句中包装函数的情况非常相似。</p><h2 id="4165" class="ne lh it bd li nm nn dn lm no np dp lq mh nq nr ls ml ns nt lu mp nu nv lw nw bi translated">捕捉某些类型的异常</h2><p id="dc74" class="pw-post-body-paragraph ly lz it ma b mb mc ju md me mf jx mg mh mi mj mk ml mm mn mo mp mq mr ms mt im bi translated">另一个选择是定义我们想要具体捕捉哪些异常类型。为此，我们需要将异常类型添加到<code class="fe nj nk nl na b">except</code>块中。</p><pre class="kj kk kl km gt mz na nb nc aw nd bi"><span id="22b7" class="ne lh it na b gy nf ng l nh ni">try:<br/>    myfunction(100, "one hundred")<br/>except TypeError:<br/>    print("Cannot sum the variables. Please pass numbers only.")</span><span id="12a9" class="ne lh it na b gy nx ng l nh ni">Cannot sum the variables. Please pass numbers only.</span></pre><p id="4e2e" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">酷毙了。它开始变得更好看了，不是吗？</p><p id="0c3a" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">现在，为了更好，我们实际上可以记录或打印异常本身。</p><pre class="kj kk kl km gt mz na nb nc aw nd bi"><span id="a558" class="ne lh it na b gy nf ng l nh ni">try:<br/>    myfunction(100, "one hundred")<br/>except TypeError as e:<br/>    print(f"Cannot sum the variables. The exception was: {e}")</span><span id="5aaa" class="ne lh it na b gy nx ng l nh ni">Cannot sum the variables. The exception was: unsupported operand type(s) for +: 'int' and 'str'</span></pre><p id="eeed" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">很好。🙂</p><p id="3308" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">此外，如果我们想以同样的方式处理这些异常类型，我们可以在一个<code class="fe nj nk nl na b">except</code>子句中捕获多个异常类型。</p><p id="ec53" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">让我们将一个未定义的变量传递给我们的函数，这样它将引发<code class="fe nj nk nl na b">NameError</code>。我们还将修改我们的<code class="fe nj nk nl na b">except</code>块来捕获<code class="fe nj nk nl na b">TypeError</code>和<code class="fe nj nk nl na b">NameError</code>，并以同样的方式处理任一异常类型。</p><pre class="kj kk kl km gt mz na nb nc aw nd bi"><span id="8728" class="ne lh it na b gy nf ng l nh ni">try:<br/>    myfunction(100, a)<br/>except (TypeError, NameError) as e:<br/>    print(f"Cannot sum the variables. The exception was {e}")</span><span id="9993" class="ne lh it na b gy nx ng l nh ni">Cannot sum the variables. The exception was name 'a' is not defined</span></pre><p id="deb5" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">注意，我们可以添加任意多的异常类型。基本上，我们只需要传递一个包含类似<code class="fe nj nk nl na b">(ExceptionType1, ExceptionType2, ExceptionType3, ..., ExceptionTypeN)</code>的异常类型的<code class="fe nj nk nl na b">tuple</code>。</p><p id="88ad" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">通常，我们会有另一个没有特定异常类型的<code class="fe nj nk nl na b">except</code>块。这样做的目的是捕捉未处理的异常类型。一个用例是当向第三方 API 发出 Http 请求时，我们可能不知道所有可能的异常类型，但是，我们仍然希望捕捉并处理它们。</p><p id="8023" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">让我们修改我们的 try except 块，以包含另一个 except 块，该块将捕获其余的异常类型。</p><pre class="kj kk kl km gt mz na nb nc aw nd bi"><span id="db90" class="ne lh it na b gy nf ng l nh ni">try:<br/>    myfunction(100, a)<br/>except (TypeError, NameError) as e:<br/>    print(f"Cannot sum the variables. The exception was {e}")<br/>except Exception as e:<br/>    print(f"Unhandled exception: {e}")</span></pre><p id="497b" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">如果我们的函数引发了除<code class="fe nj nk nl na b">TypeError</code>和<code class="fe nj nk nl na b">NameError</code>之外的任何异常，它将转到最后一个<code class="fe nj nk nl na b">except</code>块并打印<code class="fe nj nk nl na b">Unhandled exception: &lt;unhandled exception here&gt;</code>。</p></div><div class="ab cl kz la hx lb" role="separator"><span class="lc bw bk ld le lf"/><span class="lc bw bk ld le lf"/><span class="lc bw bk ld le"/></div><div class="im in io ip iq"><figure class="kj kk kl km gt kn gh gi paragraph-image"><div role="button" tabindex="0" class="ko kp di kq bf kr"><div class="gh gi oa"><img src="../Images/6ec13a0b1a174fb2d1e4f076cec39989.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/0*zCEQs9FAtjrfAI8V"/></div></div><p class="ku kv gj gh gi kw kx bd b be z dk">Photo by <a class="ae ky" href="https://unsplash.com/@hhh13?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank">傅甬 华</a> on <a class="ae ky" href="https://unsplash.com?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank">Unsplash</a></p></figure></div><div class="ab cl kz la hx lb" role="separator"><span class="lc bw bk ld le lf"/><span class="lc bw bk ld le lf"/><span class="lc bw bk ld le"/></div><div class="im in io ip iq"><h1 id="0da8" class="lg lh it bd li lj lk ll lm ln lo lp lq jz lr ka ls kc lt kd lu kf lv kg lw lx bi translated">包裹</h1><p id="8b7d" class="pw-post-body-paragraph ly lz it ma b mb mc ju md me mf jx mg mh mi mj mk ml mm mn mo mp mq mr ms mt im bi translated">哇！大家学习 Python 中的异常和异常处理做得很好。我希望那不是太糟糕😆</p><p id="b69f" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">如您所知，我们仍然可以通过添加<code class="fe nj nk nl na b">else</code>和<code class="fe nj nk nl na b">finally</code>块来扩展我们的 try except 子句。在未来的教程中会有更多的介绍。或者你想自己看，可以去看看这个<a class="ae ky" href="https://docs.python.org/3/tutorial/errors.html" rel="noopener ugc nofollow" target="_blank">教程</a>。</p><p id="c51f" class="pw-post-body-paragraph ly lz it ma b mb mu ju md me mv jx mg mh mw mj mk ml mx mn mo mp my mr ms mt im bi translated">一如既往，请随意发表任何评论或提出任何问题。🙂</p></div></div>    
</body>
</html>